docs

diff --git a/.github/workflows/documentation.yml b/.github/workflows/documentation.yml
--- a/.github/workflows/documentation.yml
+++ b/.github/workflows/documentation.yml
@@ -3,39 +3,64 @@ name: "Documentation"
 on:
   push:
     branches:
-      - gh-pages
+      - automate_docs
 
 jobs:
   docs:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v1
+    - uses: actions/checkout@v2
 
-    - name: Test building docs
-      uses: ammaraskar/sphinx-action@master
+    - name: Set up Python 3.9
+      uses: actions/setup-python@v2
       with:
-        docs-folder: "docsrc/"
-        build-command : make html
+        python-version: "3.9"
 
-    # - name: Build Sphinx Doccs
-    #   uses: ammaraskar/sphinx-action@master
-    #   with:
-    #     docs-folder: "docsrc/"
-    #     build-command : make github
+    - name: Set up dependencies
+      run: |
+        sudo apt install pandoc
+        pip install --upgrade pip 
+        pip install -r requirements.txt 
+        pip install git+https://github.com/mementum/backtrader.git@0fa63ef4a35dc53cc7320813f8b15480c8f85517#egg=backtrader
+        pip install git+https://github.com/giocaizzi/pyfolio.git
+        pip install -r docsrc/requirements.txt
+        pip install -e . 
 
-    # - name: Commit documentation changes
-    #   run: |
-    #     git clone https://github.com/giocaizzi/surfingcrypto.git --branch gh-pages --single-branch gh-pages
-    #     git config --local user.email "action@github.com"
-    #     git config --local user.name "GitHub Action"
-    #     git add .
-    #     git commit -m "Update documentation" -a || true
-    #     # The above command will fail if no changes were present, so we ignore
-    #     # the return code.
+    - name: Changelog from releases
+      uses: rhysd/changelog-from-release/action@v3
+      with:
+        file: docsrc/source/contents/changelog.md
+        commit : false
+        github_token: ${{ secrets.GITHUB_TOKEN }}
+        header: |
+          # Releases
+           
   
-    # - name: Push changes
-    #   uses: ad-m/github-push-action@master
-    #   with:
-    #     branch: gh-pages
-    #     directory: gh-pages
-    #     github_token: ${{ secrets.GITHUB_TOKEN }}
+    - name: Format Changelog headers
+      run : |
+        cd docsrc/
+        make changelog-action
+        cd ..
+  
+    - name: Building docs
+      run : |
+        cd docsrc/
+        make github-action
+        cd ..
+
+    - name: Commit documentation changes
+      run: |
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git add .
+        git commit -m "Build documentation" -a || true
+    
+      # The last command will fail if no changes were present, so we ignore
+      # the return code.
+
+
+    - name: Push changes
+      uses: ad-m/github-push-action@master
+      with:
+        branch: automate_docs
+        github_token: ${{ secrets.GITHUB_TOKEN }}
